### ISSUE TITLE
Erro na verificação dentro do BoletoAbstract->getAgenciaCodigoCedente()

### ISSUE THREAD

**Issue by kotarokikuchi** [kriansa/openboleto#20]
Olá, acho que tem um erro no método abaixo:

    /**
     * Retorna o campo Agência/Cedente do boleto
     *
     * @return string
     */
    public function getAgenciaCodigoCedente()
    {
        $agencia = $this->getAgenciaDv() ? $this->getAgencia() . '-' . $this->getAgenciaDv() : $this->getAgencia();
        $conta = $this->getContaDv() ? $this->getConta() . '-' . $this->getContaDv() : $this->getConta();
        return $agencia . ' / ' . $conta;
    }

$this->getAgenciaDv() ? e $this->getContaDv() ?  verificam se têm DVs ou não. Mas e se o dígito verificador for setado em 0(zero)? O método acaba retornando a agência e conta de forma errada e consequentemente deixando a apresentação do boleto incompleta sem os DVs.

[]s

**Comment by GTIcontrol-OFICIAL** [comment]
Na minha cidade a agencia Santander aparece nos documentos como 0040 e sem digito. Seria bom comentar que não devemos colocar o 00 no arquivo onde definimos a agencia que vai receber. No meu caso, não aparecei até tirar o 00 do 0040. Outras cidades vi que são 4 dígitos completos. E: Agencia 2535. Nestes casos não dá erro. No caso, ficou certo com o código antigo, pq assim, ao deixar 0 no digito verificador da agencia, ele retira ele totalmente.
