### ISSUE TITLE
Proposta - Código de barra impresso no formato de imagem

### ISSUE THREAD

**Issue by KennedyTedesco** [kriansa/openboleto#21]
Seria muito complicado ter a opção de gerar o código de barra no formato de imagem?

Neste formato atual, que usa CSS, o software que uso no Linux para a geração do PDF, por algum motivo, atrapalha o tamanho da fonte, fazendo com que a linha digitável seja lida errada. Se fosse uma imagem (sequência de imagens com largura pré-definida), não teria esse problema.

**Comment by Fabyo** [comment]
Pessoal, estou gerando um boleto e o numero digitavel esta saindo bem grande e ficando em 2 linhas
e o codigo de barras esta saindo em uma pagina separada

http://i.imgur.com/lNgi5Uv.png

isso é problema na conversao pra pdf ou é o layout que esta alterando algumas coisas no css do boleto?

e estou usando wkhtmltopdf, voce ainda recomendam usar H2P ?

obrigado

**Comment by kriansa** [comment]
@Fabyo Ainda recomendo o H2P. Não me recordo porém de alguma possível incompatibilidade com o wkhtmltopdf. Você está usando o zoom original? (1x)

**Comment by Fabyo** [comment]
Eu nao mexi em nenhuma propriedade de zoom
vou testar o H2P, obrigado

**Comment by kriansa** [comment]
Talvez a melhor solução pra essa funcionalidade que vem sempre sendo pedida seja a integração com o H2P ou geração direta para PDF usando ghostscript.

**Comment by Fabyo** [comment]
Otima ideia

**Comment by kriansa** [comment]
Aberto #55.
