### ISSUE TITLE
Passar o boleto para PDF ?

### ISSUE THREAD

**Issue by ale-php** [kriansa/openboleto#42]
quando converto o html para pdf usando a mpdh o codigo de barras some teria alguma maneira de gerar um pdf dos boletos?

**Comment by kriansa** [comment]
Tem sim. Criei uma biblioteca para isso: https://github.com/kriansa/h2p

**Comment by ale-php** [comment]
resolvi o problema , criei uma class mais simples usando a phantonjs.

**Comment by ggwebdev** [comment]
Consegui resolver substituindo as divs por imagens. Alterei a função **getImagemCodigoDeBarras** para gerar especificamente PDF. Ficou assim:

`/**
     * Retorna a string contendo as imagens do código de barras, segundo o padrão Febraban
     *
     * @return string
     */
    public function getImagemCodigoDeBarrasG()
    {
        $codigo = $this->getNumeroFebraban();

        $barcodes = array('00110', '10001', '01001', '11000', '00101', '10100', '01100', '00011', '10010', '01010');

        for ($f1 = 9; $f1 >= 0; $f1--) {
            for ($f2 = 9; $f2 >= 0; $f2--) {

                $f = ($f1 * 10) + $f2;
                $texto = '';

                for ($i = 1; $i < 6; $i++) {
                    $texto .= substr($barcodes[$f1], ($i - 1), 1) . substr($barcodes[$f2], ($i - 1), 1);
                }

                $barcodes[$f] = $texto;
                
            }
        }

        // Guarda inicial
        $retorno = '<div class="barcode" style="background:#eee;height:50px;overflow:hidden">' .
        '<img src="'.public_path('assets/img/slip/p.png').'" width="1" height="50">' .
        '<img src="'.public_path('assets/img/slip/b.png').'" width="1" height="50">' .
        '<img src="'.public_path('assets/img/slip/p.png').'" width="1" height="50">' .
        '<img src="'.public_path('assets/img/slip/b.png').'" width="1" height="50">';

        if (strlen($codigo) % 2 != 0) {
            $codigo = "0" . $codigo;
        }

        // Draw dos dados
        while (strlen($codigo) > 0) {

            $i = (int) round(self::caracteresEsquerda($codigo, 2));
            $codigo = self::caracteresDireita($codigo, strlen($codigo) - 2);
            $f = $barcodes[$i];

            for ($i = 1; $i < 11; $i += 2) {

                $f1 = (substr($f, ($i - 1), 1) == "0") ? '1' : '3';
                $retorno .= '<img src="'.public_path('assets/img/slip/p.png').'" width="'.$f1.'" height="50">';

                $f2 = (substr($f, $i, 1) == '0') ? '1' : '3';
                $retorno .= '<img src="'.public_path('assets/img/slip/b.png').'" width="'.$f2.'" height="50">';

            }
        }

        // Final
        return $retorno . '<img src="'.public_path('assets/img/slip/p.png').'" width="3" height="50">' .
        '<img src="'.public_path('assets/img/slip/b.png').'" width="1" height="50">' .
        '<img src="'.public_path('assets/img/slip/p.png').'" width="1" height="50">' .
        '</div>';
    }`

**Comment by ale-php** [comment]
vlw vou testar aqui

**Comment by elvysmarcos** [comment]
Essas imagens p.png, b.png, eu consgigo onde ?

**Comment by elvysmarcos** [comment]
Ja consegui criei duas imagens. valeu.

**Comment by Rctnet** [comment]
Vejam essa pulo
https://github.com/kriansa/openboleto/pull/69

**Comment by raulcgomes** [comment]
Essas imagens p.png e b.png são de qualquer dimensão?

**Comment by elvysmarcos** [comment]
1 milímetro , um branca e outra preta .

**Comment by Rctnet** [comment]
Bom dia senhores, projeto kriansa/openboleto foi descontinuado ( https://github.com/kriansa/openboleto/issues/96 ) e estamos dando continuidade em fredroo/openboleto, um exemplo de geração em pdf com a biblioteca (puro PHP) quilhasoft/jasperPHP esta disponivel em https://github.com/QuilhaSoft/JasperPHP-OpenBoleto

**Comment by raulcgomes** [comment]
@elvysmarcos poderia me passar as imagens? Eu tentei cria-las mas não funcionou 100%.

**Comment by raulcgomes** [comment]
@Rctnet obrigado, vou tentar com esse mencionado também.

**Comment by elvysmarcos** [comment]
[Bar.zip](https://github.com/kriansa/openboleto/files/2163272/Bar.zip)
@raulcgomes  segue.

**Comment by raulcgomes** [comment]
@elvysmarcos muito obrigado!

**Comment by ThiagoAlmeidaMourao** [comment]
O que é 'public_path'?

**Comment by Rctnet** [comment]
@ThiagoAlmeidaMourao , com a integração do Quilhasoft/jasperPHP esse código se tornou obsoleto, até pq ele montava o código de barras com um monte de imagens de barras pretas e brancas, que causava distorção quando aplicado zoom no arquivo PDF, prejudicando a leitura do codigo de barras por celular direto na tela do PC.

**Comment by fredroo** [comment]
@Rctnet aproveitando que você está cuidando bastante aqui do projeto, seria legal a gente adotar algumas medidas para deixar esse projeto mais útil e organizado, tipo seguir algum padrão, o que me diz?

**Comment by Rctnet** [comment]
otimo, é só me chamar, ainda tem meus contatos?

**Comment by fredroo** [comment]
@Rctnet podemos criar aqui mesmo para quem quiser dar opinião pois são os que mais usam, eu nem estou usando ainda, eu usava no multidocs.com.br, mas depois que virou obrigação ser registrado eu parei.

**Comment by Rctnet** [comment]
blz, mas agora fiquei com duvida sobre o que você quer fazer

**Comment by fredroo** [comment]
eu digo padrão de projeto php, seguir algumas coisas como se vai ser escrito em pt-BR ou EN e etc, manter um padrão de projeto, mas sem pressa e nem frescura, só pra facilitar para todos mesmo.

**Comment by Rctnet** [comment]
hum ok

**Comment by warquia** [comment]
Pessoal não estou conseguindo usar o JasperPHP - OpenBoleto não consigo encontra as classes 
JasperPHP\Pdf::prepare($report); conforme o exemplo no site

**Comment by Rctnet** [comment]
Ola, só no exemplo do readme que estava errado, nos arquivo 
https://github.com/QuilhaSoft/JasperPHP-OpenBoleto/blob/master/itauJasperA4.php

https://github.com/QuilhaSoft/JasperPHP-OpenBoleto/commit/49b69d94eca05e3843aeaf476879c1be8d1bb677

**Comment by Inovargases** [comment]
Segue o método getImagemCodigoDeBarras() alterado para imagem com base64

`public function getImagemCodigoDeBarras()
    {
        $codigo = $this->getNumeroFebraban();
        $barcodes = array('00110', '10001', '01001', '11000', '00101', '10100', '01100', '00011', '10010', '01010');

        for ($f1 = 9; $f1 >= 0; $f1--) {
            for ($f2 = 9; $f2 >= 0; $f2--) {
                $f = ($f1 * 10) + $f2;
                $texto = '';
                for ($i = 1; $i < 6; $i++) {
                    $texto .= substr($barcodes[$f1], ($i - 1), 1) . substr($barcodes[$f2], ($i - 1), 1);
                }
                $barcodes[$f] = $texto;
            }
        }

        // Imagens base64 - 1x1 pixel
        $imgPreta = 'data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs='; // 1px preto GIF
        $imgBranca = 'data:image/gif;base64,R0lGODlhAQABAPAAAP///wAAACH5BAEAAAEALAAAAAABAAEAAAICTAEAOw=='; // 1px branco GIF

        // Guarda inicial - TAMANHO REDUZIDO
        $retorno = '<div style="font-size:0px;line-height:0px;height:35px;margin:3px 0px;">' .
            '<img src="' . $imgPreta . '" style="width:1px;height:35px;display:inline-block;">' .
            '<img src="' . $imgBranca . '" style="width:1px;height:35px;display:inline-block;">' .
            '<img src="' . $imgPreta . '" style="width:1px;height:35px;display:inline-block;">' .
            '<img src="' . $imgBranca . '" style="width:1px;height:35px;display:inline-block;">';

        if (strlen($codigo) % 2 != 0) {
            $codigo = "0" . $codigo;
        }

        // Draw dos dados
        while (strlen($codigo) > 0) {
            $i = (int) round((float) self::caracteresEsquerda($codigo, 2));
            $codigo = self::caracteresDireita($codigo, strlen($codigo) - 2);
            $f = $barcodes[$i];

            for ($i = 1; $i < 11; $i += 2) {
                if (substr($f, ($i - 1), 1) == "0") {
                    $f1 = '1px'; // thin
                } else {
                    $f1 = '3px'; // large
                }
                $retorno .= '<img src="' . $imgPreta . '" style="width:' . $f1 . ';height:35px;display:inline-block;">';

                if (substr($f, $i, 1) == "0") {
                    $f2 = '1px'; // thin
                } else {
                    $f2 = '3px'; // large
                }
                $retorno .= '<img src="' . $imgBranca . '" style="width:' . $f2 . ';height:35px;display:inline-block;">';
            }
        }

        // Final
        return $retorno . '<img src="' . $imgPreta . '" style="width:3px;height:35px;display:inline-block;">' .
            '<img src="' . $imgBranca . '" style="width:1px;height:35px;display:inline-block;">' .
            '<img src="' . $imgPreta . '" style="width:1px;height:35px;display:inline-block;">' .
            '</div>';
    }`

**Comment by Inovargases** [comment]
Resolvi assim:

`
 public function getImagemCodigoDeBarras()
    {
        $codigo = $this->getNumeroFebraban();

        // Confere se tem 44 dígitos (FEBRABAN exige exatamente 44)
        $codigo = preg_replace('/\D/', '', $codigo); // remove qualquer não numérico
        if (strlen($codigo) != 44) {
            throw new \Exception("Código FEBRABAN inválido: deve conter 44 dígitos.");
        }

        // Usa a lib Picqer para gerar Interleaved 2 of 5 (padrão de boleto)
        $generator = new BarcodeGeneratorPNG();

        // parâmetros:
        // 2 = largura da barra fina em px (~0,33mm se for para PDF)
        // 50 = altura em px (~13mm em PDF 72dpi, dentro da norma FEBRABAN)
        $barcode = $generator->getBarcode($codigo, $generator::TYPE_INTERLEAVED_2_5, 2, 50);

        // Retorna a imagem embutida como <img>, igual ao seu método atual
        return '<img src="data:image/png;base64,' . base64_encode($barcode) . '" alt="Código de Barras FEBRABAN">';
    }

`

composer require picqer/php-barcode-generator
use Picqer\Barcode\BarcodeGeneratorPNG;
