### ISSUE TITLE
openboleto em JS

### ISSUE THREAD

**Issue by rtio** [kriansa/openboleto#43]
Quando sairá a versão do openboleto em JS?

**Comment by paulocastellano** [comment]
Quando sairá a versão do openboleto em JS? (2)

**Comment by HwapX** [comment]
@kriansa sem pressão, mais tem alguma novidade sobre o fork?

**Comment by kriansa** [comment]
@rtio @paulocastellano @HwapX Tenho. Vocês devem estar putos já com esses prazos infinitos, desculpa mesmo, mas eu estou trabalhando nele durante essa semana. Resolvendo bugs, criando test cases e vou lançar apenas com suporte a Banco do Brasil por enquanto.

**Comment by paulocastellano** [comment]
@kriansa Tranquilo, lança com BB e me comprometo a portar ele pra Itaú :)

**Comment by kriansa** [comment]
Conforme #53 , decidi continuar a manter o OpenBoleto. O projeto em JS ainda não está maduro o suficiente para um release e não tenho como dar uma data, mas precisa de muitos fixes agora que só poderemos emitir boletos registrados.
