### ISSUE TITLE
O que muda no código se eu adicionar uma carteira que não está configurada?

### ISSUE THREAD

**Issue by jhonnymakis** [kriansa/openboleto#49]
Ex: tenho que gerar boletos para a carteira 26 para o Bradesco, adicionei no array porém não vi na documentação se algo a mais deve ser feito. Onde eu posso obter informações? Eu posso simplesmente adicionar a carteira lá e pronto? 

Obrigado @kriansa!!  :+1:

**Comment by kriansa** [comment]
Depende da documentação do Bradesco. Algumas carteiras possuem uma maneira diferente para gerar boletos.

No caso do Bradesco creio que não terá problemas, mas agradeceria se você me dissesse se funcionou pra que possamos atualizar a classe do repo.

Abs!

**Comment by jhonnymakis** [comment]
Funcionou sim!
