### ISSUE TITLE
Como adicionar a saída em PDF/?

### ISSUE THREAD

**Issue by dlhenke** [kriansa/openboleto#54]
Existe alguma classe que eu possa utilizar para já dar saida em PDF dos boletos gerados?

**Comment by Fabyo** [comment]
Estou usando essa lib: https://github.com/KnpLabs/snappy
exemplo de uso:
$snappy = new Pdf($lib_pdf);
$snappy->generateFromHtml($boleto->getOutput(), 'boleto.pdf');

mas leia esse topico, recomendam usar H2P

https://github.com/kriansa/openboleto/issues/21

**Comment by kriansa** [comment]
Tenho uma library pra resolver esse problema.

> https://github.com/kriansa/h2p#getting-started

**Comment by dlhenke** [comment]
Ola eu vi outro projeto que já produz o arquivo em pdf..
A pergunta que fiz anteriormente foi mal formulada, 
vi que nao há uma classe para gerar o openboleto já em pdf.. então passei a trabalhar em uma.. assim que tenha algum resultado enviarei a voces.

**Comment by ggwebdev** [comment]
Só trocar as divs por imagens! Segue meu exemplo, na classe BoletoAbstract.php:

public function getImagemCodigoDeBarrasG()
    {
        $codigo = $this->getNumeroFebraban();

        $barcodes = array('00110', '10001', '01001', '11000', '00101', '10100', '01100', '00011', '10010', '01010');

        for ($f1 = 9; $f1 >= 0; $f1--) {
            for ($f2 = 9; $f2 >= 0; $f2--) {

                $f = ($f1 * 10) + $f2;
                $texto = '';

                for ($i = 1; $i < 6; $i++) {
                    $texto .= substr($barcodes[$f1], ($i - 1), 1) . substr($barcodes[$f2], ($i - 1), 1);
                }

                $barcodes[$f] = $texto;
                
            }
        }

        // Guarda inicial
        $retorno = '<div class="barcode" style="background:#eee;height:50px;overflow:hidden">' .
        '<img src="'.public_path('assets/img/slip/p.png').'" width="1" height="50">' .
        '<img src="'.public_path('assets/img/slip/b.png').'" width="1" height="50">' .
        '<img src="'.public_path('assets/img/slip/p.png').'" width="1" height="50">' .
        '<img src="'.public_path('assets/img/slip/b.png').'" width="1" height="50">';

        if (strlen($codigo) % 2 != 0) {
            $codigo = "0" . $codigo;
        }

        // Draw dos dados
        while (strlen($codigo) > 0) {

            $i = (int) round(self::caracteresEsquerda($codigo, 2));
            $codigo = self::caracteresDireita($codigo, strlen($codigo) - 2);
            $f = $barcodes[$i];

            for ($i = 1; $i < 11; $i += 2) {

                $f1 = (substr($f, ($i - 1), 1) == "0") ? '1' : '3';
                $retorno .= '<img src="'.public_path('assets/img/slip/p.png').'" width="'.$f1.'" height="50">';

                $f2 = (substr($f, $i, 1) == '0') ? '1' : '3';
                $retorno .= '<img src="'.public_path('assets/img/slip/b.png').'" width="'.$f2.'" height="50">';

            }
        }

**Comment by Rctnet** [comment]
Vejam essa pull
https://github.com/kriansa/openboleto/pull/69
