### ISSUE TITLE
Desconto

### ISSUE THREAD

**Issue by realcofre** [kriansa/openboleto#84]
Quando o boleto for emitido e o emissor desejar oferecer um desconto para o cliente que pagar antecipado, essa informação será destacada no campo descontos/abatimentos no espelho do boleto? Ou devo informar esses dados apenas no arquivo remessa?

**Comment by Rctnet** [comment]
Bom dia @realcofre , você deve fazer isso nos dois, no boleto impresso para que o pagador saiba que existe o desconto e na remessa para que sistema do banco saiba quando permitir desconto no caso de pagamento via bankline

**Comment by realcofre** [comment]
![exemplo_boleto](https://cloud.githubusercontent.com/assets/17703015/25398200/74ca7496-29c1-11e7-804f-bad7d3581712.png)

Boa tarde @Rctnet então na ficha de compensação as informações ficarão como destaquei na imagem anexa? (campos marcados com vermelho 1 e 2)

**Comment by Rctnet** [comment]
na verdade não, o campo 2 indicaria que o desconto existe em qualquer situação, ficaria mantida somente a instrução 1 já no arquivo de remessa é (dependendo do banco) possível incluir vários níveis de desconto, claro que sempre incluindo os dizeres correspondentes para cada nível nas instruções 1

**Comment by realcofre** [comment]
Obrigado @Rctnet .
