### ISSUE TITLE
Código de movimentação de remessa

### ISSUE THREAD

**Issue by realcofre** [kriansa/openboleto#87]
No Manual de Procedimentos Operacionais para Troca de Arquivos – Cobrança Bradesco existe uma lista que identifica as ocorrências na remessa, por exemplo:

01..Remessa
02..Pedido de baixa
etc

A minha dúvida é a seguinte, essa relação de códigos é comum a todos os bancos?

**Comment by Rctnet** [comment]
Não são iguais, o 1 e dois 2 são mas o resto não, então mantenho no meu sistema um tabela em banco de dados com os códigos  e o banco a que se referem e Também o nome amigável para o usuário, minha tabela só tem para o Itaú  que é o único que uso no momento. Mas como a tabela está pronta e posso selecionar isso antes de enviar, funcionaria muito bem. Aproveite e visite meu projeto Opencnabphp.

**Comment by realcofre** [comment]
Ok, obrigado. Deu tudo certo.
