### ISSUE TITLE
Envio de remessa automático

### ISSUE THREAD

**Issue by realcofre** [kriansa/openboleto#89]
Olá, 

Normalmente os clientes que utilizam boleto enviam suas remessas manualmente pelo aplicativo disponibilizado pelo banco. Existe a possibilidade do envio da remessa ser automático? Como fazer? Alguém aqui faz a transferência da remessa automática para o banco?

**Comment by gcarneiro** [comment]
Eu tento realizar essa integração faz tempo, mas é bem complicado lidar com os bancos. Eles não tem documentação, todo o processo precisa passar por pessoas diferentes e é tudo muito demorado. Acabei por me contentar com a solução manual de subir e baixar os arquivos.

Enquanto estava tentando descobrir sobre isso, descobri que eles utilizam uma tecnologia chamada WAN, eles tentam oferecer empresas que cobram para fazer isso, consegui orçamentos de 300 a 1000 por mês!!! Pelo que entendi tudo é feito através de uma conta de ftp onde são escritos todos os arquivos de retorno e você pode escrever os de remessa.

Cheguei mais longe tentando com o Santander, onde tive contato com um gerente regional que acabou por sumir após já termos todos os layouts dos arquivos homologados. Acabei desistindo de correr atrás por enquanto.

**Comment by realcofre** [comment]
Ok, obrigado

**Comment by khrisnet** [comment]
Também corri bastante atrás de uma solução para isso. O que consegui fazer realmente até o momento foi só para o Bradesco. Que fuçando no NetEmpresa vi uma breve documentação e modelos de arquivos que possibilitam integração de envio e recebimento da remessa via WebService. Inclusive muito bem desenvolvido e documentado, onde utilizo até o presente momento.

**Comment by fabiomigliorini** [comment]
Bom dia, você consegue passar o nome do produto e a documentação que
utilizou???

Trabalho com Bradesco também, mas aqui na agência ninguém sabe disso...
Segundo eles não existe...

Com a documentação é mais fácil explicar pra eles que isso existe para
pedir ajuda na integração...

Obrigado

Em 25 de ago de 2017 1:21 PM, "Khristian Algarves" <notifications@github.com>
escreveu:

**Comment by khrisnet** [comment]
@fabiomigliorini, desculpa estive fora durante um tempo e acabei não vendo sua interação.
Mas pode deixar vou verificar e te passo. Faz uns 2 anos que desenvolvi e não me recordo.

**Comment by khrisnet** [comment]
Boa tarde @fabiomigliorini 

Conforme comentei, vou deixar um link para você ter acesso a documentação do WebTA que a principio pelo que olhei é o nome do serviço oferecido pelo Bradesco.

[Documentação WebTA](https://www.dropbox.com/s/6xg1twtsqlf9slr/bradesco_webta.zip?dl=0)

_Obs: inclusive meu intuito é disponibilizar aqui no github uma rotina pronta para o pessoal utilizar. Mas devido a falta de tempo no momento e pelo fato de estar muito acoplado a nossa necessidade ainda não consegui infelizmente._

**Os passos:**

1. Através do NETEmpresa tem um recurso para você gerar as 2 chaves (criptografiaYYYYMMDDHHmmss.bin e transferenciaYYYYMMDDHHmmss.bin) seguido de uma senha que você terá que definir. Irá utilizar na rotina de criptograr e descriptografar os arquivos manipulados via WebService.

2. Optar por utilizar o próprio monitor do Bradesco para manipulação, que é compatível tanto com plataforma Microsoft (Windows) como Unix. Ou em JAVA utilizando libs que disponibilizam para você mesmo implementar a rotina da forma que achar melhor.

**Resumindo o processo se dá da seguinte forma:**

- Você gera o arquivo de remessa de acordo com o layout homologado pelo seu sistema normalmente;
- Depois você criptografa esse arquivo utilizando as chaves (.bin) juntamente com a sua senha;
- Ai sim transmite esse arquivo criptografado via WebService para o Bradesco;
- ... o mesmo processo ocorre para obter o arquivo de retorno e processa-lo no seu sistema;

Qualquer dúvida se puder auxiliar em algo mais fico à disposição
Espero ter ajudado em algo

Abraço

**Comment by alexdeoliveira** [comment]
Olá! Gostaria de contribuir com essa Issue enviando um link que descobri para registro de boletos no BB:
- Basta efetuar um GET com os parâmetros na própria URL para o endereço: https://mpag.bb.com.br/site/mpag/

Valeu!

**Comment by julianoribero** [comment]
Olá pessoal. Existe essa opção para caixa econômica, alguém tem esse
conhecimento?

Obrigado!




Em seg, 4 de fev de 2019 às 15:18, Aléx de Oliveira <
notifications@github.com> escreveu:

**Comment by julianoribero** [comment]
Muito obrigado... Vamos aguardar!
*Atenciosamente**,*
*Juliano Ribeiro*
*(062) 9981-1870*


Em seg, 4 de fev de 2019 às 15:26, Aléx de Oliveira <
notifications@github.com> escreveu:

**Comment by ExpeditoMoraes** [comment]
Olá pessoal, sei que faz algum tempo que essa discussão não é comentada... Galera, estou no processo de implementação do webservice bradesco de registro e geração de boletos. Segui o manual, falei com o suporte webservice bradesco... Consegui assinar o JSON e ao testar o webservice no postman consigo o retorno de 200 sucesso, porém a api não me retorna nada, o que teoricamente era pra me retornar no mínimo um url com o arquivo gerado. Desse modo, obtenho 200 sucesso, mas não consigo nenhum dado, nem arquivo, nem nada nesse sentido. O meu app está pronto, faltando apenas a principal funcionalidade: Através do envio de remessa por parte do usuário, o app converterá em boletos bradesco pdf. Sei que a apresentação do boleto é de responsabilidade do desenvolvedor. Mas como saber se algo está sendo gerado para seguir com a implementação? Por gentileza, me ajudem nesse sentido. Obrigado a todos.
