### ISSUE TITLE
DV - Banco do Brasil - Erro

### ISSUE THREAD

**Issue by fernandokohler** [kriansa/openboleto#93]
Olá,
Estou tendo problemas com a geração do boleto para o Banco do Brasil, a linha digitável esta 100%, porém quando vai gerar o nosso número ele não coloca o DV, mas quando solicito a segunda via no banco do brasil ele possui o DV.
Ex:
Banco do Brasil : 12345670000111111-2
OpenBoleto      :  12345670000111111

Alguém pode me ajudar?

**Comment by realcofre** [comment]
No fonte do Banco do Brasil encontrei isso aqui 

`// Quando o nosso número tiver menos de 17 dígitos, colocar o dígito
        if (strlen($numero) < 17) {
            $modulo = static::modulo11($numero);
            $numero .= '-' . $modulo['digito'];
        }
`

Desse modo não será gerado o dígito verificador.

**Comment by realcofre** [comment]
No layout CNAB240 para geração do arquivo remessa de novembro/2016 tem o seguinte:


c) Para número de convênio de 7 posições (acima de 1.000.000) informar o nosso número com17 posições sem DV, sendo as 7 primeiras posições o número do convênio e as 10 posições seguintesum número sequencial para controle. Esse é o padrão mais utilizado atualmente.Exemplo: CONVÊNIOS DE 1.000.000 ATÉ 9.999.99912345671234567890CCCCCCCSSSSSSSSSSOnde: C = Convênio S = Sequencial
--

**Comment by realcofre** [comment]
No layout do boleto informa que realmente o nosso número para convênio de 7 posições é sem o dígito verificador.

![image](https://user-images.githubusercontent.com/17703015/29718394-0af9ab7c-8989-11e7-9a5e-d73ffd380604.png)
