### ISSUE TITLE
Boleto Banco do Brasil

### ISSUE THREAD

**Issue by realcofre** [kriansa/openboleto#94]
Olá,

No boleto do Banco do Brasil é obrigatório a indicação no campo Carteira do código de variação da carteira? Por exemplo, um cliente que temos aqui ele emite boleto pelo software do banco e no campo carteira vem assim 17/19. Essa indicação da variação é obrigatória? Como fazer isso no openboleto?
Grato pela atenção.

**Comment by danbonattis** [comment]
Bom dia, @realcofre.
Eu testei com carteira 17 variação 19, e carteira 17 variação 27 e ambos as linhas digitáveis e o credito deram certo. Só não sei para gerar arquivo de remessa.

**Comment by realcofre** [comment]
Ok, obrigado.
